services:

  db:
    build: db
    container_name: ${COMPOSE_PROJECT_NAME}_db
    restart: on-failure
    command: --sql_mode="" --innodb-buffer-pool-size=2G --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: docker_root
      MYSQL_DATABASE: onboard
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: Europe/Warsaw
    volumes:
      - db-data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT_MAP}:3306"

  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
      target: base
    environment:
      DB_HOST: db
      DB_NAME: onboard
      DB_USER: docker
      DB_PASS: docker
      APPLICATION_ENV: development
      TZ: Europe/Warsaw
    depends_on:
      - db
    restart: on-failure
    networks:
      default:
        aliases:
          - app_test

volumes:
  db-data: